config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :platforms

      resources :notes

      resources :statuses

      resources :ratings

      resources :users

      resources :developers

      resources :publishers

      resources :video_games
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "video_games#index"
  resources :platforms
  resources :notes
  resources :statuses
  resources :ratings
  devise_for :users
  resources :users
  resources :developers
  resources :publishers
  resources :video_games
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/note.rb
class Note < ApplicationRecord
  # Direct associations

  belongs_to :user

  belongs_to :game,
             class_name: "VideoGame"

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    user.to_s
  end
end

app/controllers/api/v1/notes_controller.rb
class Api::V1::NotesController < Api::V1::GraphitiController
  def index
    notes = NoteResource.all(params)
    respond_with(notes)
  end

  def show
    note = NoteResource.find(params)
    respond_with(note)
  end

  def create
    note = NoteResource.build(params)

    if note.save
      render jsonapi: note, status: :created
    else
      render jsonapi_errors: note
    end
  end

  def update
    note = NoteResource.find(params)

    if note.update_attributes
      render jsonapi: note
    else
      render jsonapi_errors: note
    end
  end

  def destroy
    note = NoteResource.find(params)

    if note.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: note
    end
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: %i[show edit update destroy]

  def index
    @q = Note.ransack(params[:q])
    @notes = @q.result(distinct: true).includes(:game,
                                                :user).page(params[:page]).per(10)
  end

  def show; end

  def new
    @note = Note.new
  end

  def edit; end

  def create
    @note = Note.new(note_params)

    if @note.save
      message = "Note was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @note, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @note.update(note_params)
      redirect_to @note, notice: "Note was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @note.destroy
    message = "Note was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to notes_url, notice: message
    end
  end

  private

  def set_note
    @note = Note.find(params[:id])
  end

  def note_params
    params.require(:note).permit(:user_id, :game_id, :note)
  end
end

app/views/notes/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Note #<%= note.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>User</dt>
      <dd>
        <% if @note.user.present? %>
          <%= link_to note.user, note.user %>
        <% end %>
      </dd>

      <dt>Game</dt>
      <dd>
        <% if @note.game.present? %>
          <%= link_to note.game, note.game %>
        <% end %>
      </dd>

      <dt>Note</dt>
      <dd><%= note.note %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back note, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_note_url(note), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to note, method: :delete, data: { confirm: "Do you really want to delete this note?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(note.updated_at) %> ago
  </div>
</div>

app/views/notes/_form.html.erb
<% was_validated = note.errors.any? %>

<%= form_with(model: note, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% user_class = "form-control" %>
    <% user_was_invalid = note.errors.include?(:user) %>

    <% if was_validated %>
      <% if user_was_invalid %>
        <% user_class << " is-invalid" %>
      <% else %>
        <% user_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
    <% if user_was_invalid %>
      <% note.errors.full_messages_for(:user).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% game_class = "form-control" %>
    <% game_was_invalid = note.errors.include?(:game) %>

    <% if was_validated %>
      <% if game_was_invalid %>
        <% game_class << " is-invalid" %>
      <% else %>
        <% game_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :game_id %>
    <%= f.collection_select :game_id, VideoGame.all, :id, :to_s, {}, class: "form-control" %>
    <% if game_was_invalid %>
      <% note.errors.full_messages_for(:game).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% note_class = "form-control" %>
    <% note_was_invalid = note.errors.include?(:note) %>

    <% if was_validated %>
      <% if note_was_invalid %>
        <% note_class << " is-invalid" %>
      <% else %>
        <% note_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :note %>
    <%= f.text_area :note, class: note_class, placeholder: "Enter note" %>
    <% if note_was_invalid %>
      <% note.errors.full_messages_for(:note).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/notes/_list_item.html.erb
<%= link_to note, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= note %>
    <small class="text-muted">
      <%= time_ago_in_words(note.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/notes/_notes_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "notes_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :note_cont, "Note contains" %>
    <%= f.text_field :note_cont, :class => "form-control", :placeholder => "Note contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :game_name_cont, "Game name contains" %>
    <%= f.text_field :game_name_cont, :class => "form-control", :placeholder => "Game name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :user_email_cont, "User email contains" %>
    <%= f.text_field :user_email_cont, :class => "form-control", :placeholder => "User email contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/notes" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#notes_filters">
  Show filters
</a>

app/views/notes/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Note #<%= @note.id %>
      </h2>

      <div class="card-body">
        <%= render "form", note: @note %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/notes/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Notes

      <%= link_to new_note_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "notes/notes_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Notes

        <%= link_to new_note_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @notes, partial: "list_item", as: :note %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @notes, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/notes/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Note
      </h2>

      <div class="card-body">
        <%= render "form", note: @note %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/notes/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @note, partial: "card", as: :note %>
  </div>
</div>