config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :platforms

      resources :notes

      resources :statuses

      resources :ratings

      resources :users

      resources :developers

      resources :publishers

      resources :video_games
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "video_games#index"
  resources :platforms
  resources :notes
  resources :statuses
  resources :ratings
  devise_for :users
  resources :users
  resources :developers
  resources :publishers
  resources :video_games
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/api/v1/platforms_controller.rb
class Api::V1::PlatformsController < Api::V1::GraphitiController
  def index
    platforms = PlatformResource.all(params)
    respond_with(platforms)
  end

  def show
    platform = PlatformResource.find(params)
    respond_with(platform)
  end

  def create
    platform = PlatformResource.build(params)

    if platform.save
      render jsonapi: platform, status: :created
    else
      render jsonapi_errors: platform
    end
  end

  def update
    platform = PlatformResource.find(params)

    if platform.update_attributes
      render jsonapi: platform
    else
      render jsonapi_errors: platform
    end
  end

  def destroy
    platform = PlatformResource.find(params)

    if platform.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: platform
    end
  end
end

app/controllers/platforms_controller.rb
class PlatformsController < ApplicationController
  before_action :set_platform, only: %i[show edit update destroy]

  def index
    @q = Platform.ransack(params[:q])
    @platforms = @q.result(distinct: true).includes(:video_games).page(params[:page]).per(10)
  end

  def show
    @video_game = VideoGame.new
  end

  def new
    @platform = Platform.new
  end

  def edit; end

  def create
    @platform = Platform.new(platform_params)

    if @platform.save
      redirect_to @platform, notice: "Platform was successfully created."
    else
      render :new
    end
  end

  def update
    if @platform.update(platform_params)
      redirect_to @platform, notice: "Platform was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @platform.destroy
    redirect_to platforms_url, notice: "Platform was successfully destroyed."
  end

  private

  def set_platform
    @platform = Platform.find(params[:id])
  end

  def platform_params
    params.require(:platform).permit(:name)
  end
end

app/views/platforms/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Platform #<%= platform.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Name</dt>
      <dd><%= platform.name %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back platform, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_platform_url(platform), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to platform, method: :delete, data: { confirm: "Do you really want to delete this platform?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(platform.updated_at) %> ago
  </div>
</div>

app/views/platforms/_form.html.erb
<% was_validated = platform.errors.any? %>

<%= form_with(model: platform, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% name_class = "form-control" %>
    <% name_was_invalid = platform.errors.include?(:name) %>

    <% if was_validated %>
      <% if name_was_invalid %>
        <% name_class << " is-invalid" %>
      <% else %>
        <% name_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :name %>
    <%= f.text_field :name, class: name_class, placeholder: "Enter name" %>
    <% if name_was_invalid %>
      <% platform.errors.full_messages_for(:name).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/platforms/_list_item.html.erb
<%= link_to platform, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= platform %>
    <small class="text-muted">
      <%= time_ago_in_words(platform.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/platforms/_platform_video_games.html.erb
<div class="card">
  <div class="card-header d-flex align-items-center justify-content-between">
    Video Games

    <a data-toggle="collapse" href="#platform_video_games_new_form">
      Add video game
    </a>
  </div>

  <ul class="list-group list-group-flush">
    <% @platform.video_games.each do |video_game| %>
      <li class="list-group-item d-flex align-items-center justify-content-between">
        <%= link_to video_game, video_game %>

        <%= link_to video_game, method: :delete, data: { confirm: "Do you really want to delete this video_game" } do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>

      </li>
    <% end %>

    <div class="card-footer">
      <div class="collapse" id="platform_video_games_new_form">
        <%= render partial: "platforms/platform_video_games_new_form" %>
      </div>
    </div>

  </ul>
</div>

app/views/platforms/_platform_video_games_new_form.html.erb
<%= form_with(model: @video_game, local: true) do |f| %>

  <div class="form-group">
    <%= f.label :name %>

    <%= f.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :release_date %>

    <%= f.date_select :release_date, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :image %>

    <%= f.file_field :image, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :publisher_id %>

    <%= f.collection_select :publisher_id, Publisher.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :developer_id %>

    <%= f.collection_select :developer_id, Developer.all, :id, :to_s, {}, class: "form-control" %>
  </div>

  <%= f.hidden_field :platform_id, value: @platform.id %>

  <%= f.submit "Create video game", class: "btn btn-block btn-outline-secondary" %>
<% end %>

app/views/platforms/_platforms_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "platforms_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :name_cont, "Name contains" %>
    <%= f.text_field :name_cont, :class => "form-control", :placeholder => "Name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :video_games_name_cont, "Video games name contains" %>
    <%= f.text_field :video_games_name_cont, :class => "form-control", :placeholder => "Video games name contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/platforms" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#platforms_filters">
  Show filters
</a>

app/views/platforms/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Platform #<%= @platform.id %>
      </h2>

      <div class="card-body">
        <%= render "form", platform: @platform %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/platforms/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Platforms

      <%= link_to new_platform_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "platforms/platforms_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Platforms

        <%= link_to new_platform_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @platforms, partial: "list_item", as: :platform %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @platforms, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/platforms/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Platform
      </h2>

      <div class="card-body">
        <%= render "form", platform: @platform %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/platforms/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @platform, partial: "card", as: :platform %>
  </div>
</div>

<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render partial: "platforms/platform_video_games" %>
  </div>
</div>