config/routes.rb
Rails.application.routes.draw do
  scope path: ApplicationResource.endpoint_namespace,
        defaults: { format: :jsonapi } do
    scope module: "api/v1", as: "api" do
      resources :platforms

      resources :notes

      resources :statuses

      resources :ratings

      resources :users

      resources :developers

      resources :publishers

      resources :video_games
    end
    mount VandalUi::Engine, at: "/vandal"
    # your routes go here
  end
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  root to: "video_games#index"
  resources :platforms
  resources :notes
  resources :statuses
  resources :ratings
  devise_for :users
  resources :users
  resources :developers
  resources :publishers
  resources :video_games
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/rating.rb
class Rating < ApplicationRecord
  # Direct associations

  belongs_to :user

  belongs_to :game,
             class_name: "VideoGame"

  # Indirect associations

  # Validations

  # Scopes

  def to_s
    game.to_s
  end
end

app/controllers/api/v1/ratings_controller.rb
class Api::V1::RatingsController < Api::V1::GraphitiController
  def index
    ratings = RatingResource.all(params)
    respond_with(ratings)
  end

  def show
    rating = RatingResource.find(params)
    respond_with(rating)
  end

  def create
    rating = RatingResource.build(params)

    if rating.save
      render jsonapi: rating, status: :created
    else
      render jsonapi_errors: rating
    end
  end

  def update
    rating = RatingResource.find(params)

    if rating.update_attributes
      render jsonapi: rating
    else
      render jsonapi_errors: rating
    end
  end

  def destroy
    rating = RatingResource.find(params)

    if rating.destroy
      render jsonapi: { meta: {} }, status: :ok
    else
      render jsonapi_errors: rating
    end
  end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :set_rating, only: %i[show edit update destroy]

  def index
    @q = Rating.ransack(params[:q])
    @ratings = @q.result(distinct: true).includes(:game,
                                                  :user).page(params[:page]).per(10)
  end

  def show; end

  def new
    @rating = Rating.new
  end

  def edit; end

  def create
    @rating = Rating.new(rating_params)

    if @rating.save
      message = "Rating was successfully created."
      if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
        redirect_back fallback_location: request.referer, notice: message
      else
        redirect_to @rating, notice: message
      end
    else
      render :new
    end
  end

  def update
    if @rating.update(rating_params)
      redirect_to @rating, notice: "Rating was successfully updated."
    else
      render :edit
    end
  end

  def destroy
    @rating.destroy
    message = "Rating was successfully deleted."
    if Rails.application.routes.recognize_path(request.referer)[:controller] != Rails.application.routes.recognize_path(request.path)[:controller]
      redirect_back fallback_location: request.referer, notice: message
    else
      redirect_to ratings_url, notice: message
    end
  end

  private

  def set_rating
    @rating = Rating.find(params[:id])
  end

  def rating_params
    params.require(:rating).permit(:game_id, :user_id, :rating, :review)
  end
end

app/views/ratings/_card.html.erb
<div class="card mb-3">
  <h2 class="card-header h4">
    Rating #<%= rating.id %>
  </h2>

  <div class="card-body">
    <dl class="mb-1">
      <dt>Game</dt>
      <dd>
        <% if @rating.game.present? %>
          <%= link_to rating.game, rating.game %>
        <% end %>
      </dd>

      <dt>User</dt>
      <dd>
        <% if @rating.user.present? %>
          <%= link_to rating.user, rating.user %>
        <% end %>
      </dd>

      <dt>Rating</dt>
      <dd><%= rating.rating %></dd>

      <dt>Review</dt>
      <dd><%= rating.review %></dd>

    </dl>

    <div class="row">
      <div class="col">
        <%= link_to_show_or_back rating, '<i class="fas fa-search-plus"></i>'.html_safe, '<i class="fas fa-chevron-left"></i>'.html_safe, class: "btn btn-block btn-outline-secondary" %>
      </div>

      <div class="col">
        <%= link_to edit_rating_url(rating), class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-edit"></i>
        <% end %>
      </div>

      <div class="col">
        <%= link_to rating, method: :delete, data: { confirm: "Do you really want to delete this rating?" }, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-trash-alt"></i>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card-footer text-muted">
    Last updated <%= time_ago_in_words(rating.updated_at) %> ago
  </div>
</div>

app/views/ratings/_form.html.erb
<% was_validated = rating.errors.any? %>

<%= form_with(model: rating, local: true, novalidate: true, class: "mb-3") do |f| %>
  <div class="form-group">
    <% game_class = "form-control" %>
    <% game_was_invalid = rating.errors.include?(:game) %>

    <% if was_validated %>
      <% if game_was_invalid %>
        <% game_class << " is-invalid" %>
      <% else %>
        <% game_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :game_id %>
    <%= f.collection_select :game_id, VideoGame.all, :id, :to_s, {}, class: "form-control" %>
    <% if game_was_invalid %>
      <% rating.errors.full_messages_for(:game).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% user_class = "form-control" %>
    <% user_was_invalid = rating.errors.include?(:user) %>

    <% if was_validated %>
      <% if user_was_invalid %>
        <% user_class << " is-invalid" %>
      <% else %>
        <% user_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :user_id %>
    <%= f.collection_select :user_id, User.all, :id, :to_s, {}, class: "form-control" %>
    <% if user_was_invalid %>
      <% rating.errors.full_messages_for(:user).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% rating_class = "form-control" %>
    <% rating_was_invalid = rating.errors.include?(:rating) %>

    <% if was_validated %>
      <% if rating_was_invalid %>
        <% rating_class << " is-invalid" %>
      <% else %>
        <% rating_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :rating %>
    <%= f.number_field :rating, class: rating_class, placeholder: "Enter rating" %>
    <% if rating_was_invalid %>
      <% rating.errors.full_messages_for(:rating).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="form-group">
    <% review_class = "form-control" %>
    <% review_was_invalid = rating.errors.include?(:review) %>

    <% if was_validated %>
      <% if review_was_invalid %>
        <% review_class << " is-invalid" %>
      <% else %>
        <% review_class << " is-valid" %>
      <% end %>
    <% end %>

    <%= f.label :review %>
    <%= f.text_area :review, class: review_class, placeholder: "Enter review" %>
    <% if review_was_invalid %>
      <% rating.errors.full_messages_for(:review).each do |message| %>
        <div class="invalid-feedback d-flex">
          <%= message %>
        </div>
      <% end %>
    <% end %>
  </div>
  <%= f.button class: "btn btn-outline-secondary btn-block" %>
<% end %>

app/views/ratings/_list_item.html.erb
<%= link_to rating, class: "list-group-item list-group-item-action d-flex align-items-center justify-content-between" do %>
  <div>
    <%= rating %>
    <small class="text-muted">
      <%= time_ago_in_words(rating.updated_at) %> ago
    </small>
  </div>

  <span class="btn btn-sm btn-outline-secondary">
    <i class="fas fa-chevron-right fa-fw"></i>
  </span>
<% end %>

app/views/ratings/_ratings_search_form.html.erb
<%= search_form_for @q, :class => collapse_search_form, :id => "ratings_filters" do |f| %>
  <p class="lead">Narrow results:</p>

  <div class="form-group">
    <%= f.label :review_cont, "Review contains" %>
    <%= f.text_field :review_cont, :class => "form-control", :placeholder => "Review contains" %>
  </div>

  <div class="form-group">
    <%= f.label :rating, "Rating" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <%= f.text_field :rating_gteq, :class => "form-control", :placeholder => "Rating greater than or equal to" %>
      </div>
      <div class='col-md-6'>
        <%= f.text_field :rating_lteq, :class => "form-control", :placeholder => "Rating less than or equal to" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :created_at, "Created at" %>
    <div class="row">
      <div class='col-md-6 mb-1'>
        <div class='input-group date' id='created_atgteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_gteq, :class => "form-control datetimepicker-input", :placeholder => "Created at greater than or equal to", :data => {:target => '#created_atgteqPicker'} %>
          <div class="input-group-append" data-target='#created_atgteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>

      <div class='col-md-6'>
        <div class='input-group date' id='created_atlteqPicker' data-target-input="nearest">
          <%= f.text_field :created_at_lteq, :class => "form-control datetimepicker-input", :placeholder => "Created at less than or equal to", :data => {:target => '#created_atlteqPicker'} %>
          <div class="input-group-append" data-target='#created_atlteqPicker' data-toggle="datetimepicker">
            <div class="input-group-text"><i class="fa fa-calendar"></i></div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <script type="text/javascript">
      $(function () {
          $('#created_atgteqPicker').datetimepicker({
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atlteqPicker').datetimepicker({
              useCurrent: false,
              format: 'YYYY-MM-DD hh:mm:SS'
          });
          $('#created_atgteqPicker').on("dp.change", function (e) {
              $('#created_atlteqPicker').data("DateTimePicker").minDate(e.date);
          });
          $('#created_atlteqPicker').on("dp.change", function (e) {
              $('#created_atgteqPicker').data("DateTimePicker").maxDate(e.date);
          });
      });
  </script>


  <div class="form-group">
    <%= f.label :game_name_cont, "Game name contains" %>
    <%= f.text_field :game_name_cont, :class => "form-control", :placeholder => "Game name contains" %>
  </div>

  <div class="form-group">
    <%= f.label :user_email_cont, "User email contains" %>
    <%= f.text_field :user_email_cont, :class => "form-control", :placeholder => "User email contains" %>
  </div>


  <%= f.submit :class => "btn btn-primary btn-block mb-1" %>

  <a href="/ratings" class="btn btn-outline-secondary btn-block mb-1">Clear filters</a>

<% end %>

<a class="btn btn-outline-secondary btn-block mb-1" data-toggle="collapse" href="#ratings_filters">
  Show filters
</a>

app/views/ratings/edit.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        Edit Rating #<%= @rating.id %>
      </h2>

      <div class="card-body">
        <%= render "form", rating: @rating %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/ratings/index.html.erb
<div class="row mb-3">
  <div class="col-md-12">
    <h1 class="display-4">
      Ratings

      <%= link_to new_rating_path, class: "btn btn-lg btn-outline-secondary" do %>
        <i class="fas fa-plus fa-fw"></i>
      <% end %>
    </h1>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mb-3">
    <%= render partial: "ratings/ratings_search_form" %>
  </div>
</div>




<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h1 class="card-header h4 d-flex align-items-center justify-content-between">
        Ratings

        <%= link_to new_rating_path, class: "btn btn-sm btn-outline-secondary" do %>
          <i class="fas fa-plus fa-fw"></i>
        <% end %>
      </h1>

      <div class="list-group list-group-flush">
        <%= render collection: @ratings, partial: "list_item", as: :rating %>
      </div>
      <div class="card-footer d-flex justify-content-center">
        <%= paginate @ratings, theme: 'twitter-bootstrap-4' %>
      </div>

    </div>
  </div>
</div>

app/views/ratings/new.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <div class="card">
      <h2 class="card-header h4">
        New Rating
      </h2>

      <div class="card-body">
        <%= render "form", rating: @rating %>

        <%= link_to :back, class: "btn btn-block btn-outline-secondary" do %>
          <i class="fas fa-chevron-left fa-fw"></i>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/ratings/show.html.erb
<div class="row justify-content-center mb-3">
  <div class="col-md-8">
    <%= render object: @rating, partial: "card", as: :rating %>
  </div>
</div>